export const FIND_HOUSE_BY_ID_REQUEST='FIND_HOUSE_BY_ID_REQUEST';
export const FIND_HOUSE_BY_ID_SUCCESS='FIND_HOUSE_BY_ID_SUCCESS';
export const FIND_HOUSE_BY_ID_FAILURE='FIND_HOUSE_BY_ID_FAILURE';

export const FIND_HOUSE_REQUEST='FIND_HOUSE_REQUEST';
export const FIND_HOUSE_SUCCESS='FIND_HOUSE_SUCCESS';
export const FIND_HOUSE_FAILURE='FIND_HOUSE_FAILURE';

export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE';

